'use strict';
const projects={
flame:{extra:[["Sådan fungerer motoren", "En Flame Eater Engine er en vakuummotor. Den trækker varme gasser fra en flamme ind i cylinderen. Når ventilen lukker, og gasserne køler af, falder trykket. Det højere lufttryk udenfor driver stemplet, mens svinghjulet hjælper bevægelsen videre til næste cyklus."], ["Fremstilling", "De drejede dele fremstillede jeg på vores Weiler Matador. De manuelt fræsede dele blev bearbejdet på vores Deckel-fræsere, og til CNC-fræsningen brugte jeg vores Haas Mini Mill."], ["Resultat og næste forbedring", "Motoren fungerede fint ved den første test. En videreudvikling ville især handle om selve motorens design."]],title:'Flame Eater Engine',index:'01 / MODELMOTOR',image:'flame-engine.webp',material:'Messing · aluminium · stål',process:"Manuel drejning og fræsning · CNC-fræsning",focus:'Pasning mellem cylinder og stempel',intro:"Jeg fremstillede alle delene til motoren selv bortset fra kuglelejerne, som er indkøbt. Jeg tog udgangspunkt i et eksisterende design fra en hjemmeside, som en medstuderende anbefalede. Motoren fungerede fint ved den første test.",challenge:'Den største udfordring var at få pasningen mellem cylinder og stempel rigtig. Her mødes kravene til bevægelse og tæthed i to dele, der skal fungere sammen.',solution:"Pasningen mellem stempel og cylinder krævede flere justeringer. Jeg tog gentagne spring passes på begge dele og kontrollerede løbende med GO/NO-GO-lærer og ved at afprøve delene sammen. Målet var en jævn bevægelse med lav friktion, da motoren kører tørt uden smøring.",learning:"Projektet lærte mig at arbejde tålmodigt med pasninger og kontrollere undervejs. Hvis jeg skulle videreudvikle motoren, ville jeg først arbejde med selve designet.",docs:[['FAI 01','Cylinder og stempel','fai-01.html'],['FAI 02','Knast (Cam Disc)','fai-02-camdisc.html'],['FAI 03','Svinghjul','fai-03-flywheel.html']]},
ring:{extra:[["Opgaven", "Bevar idéen og det overordnede design fra det eksisterende værktøj, men udfør det i aluminium og stål til brug på GF1."], ["Resultatet", "Efter fremstillingen testede vi ringbøjeren sammen. Den fungerede uden problemer."]],title:'Ring Bender',index:'02 / SPECIALVÆRKTØJ',image:'ring-bender.webp',material:"Aluminium · stål",process:'CNC-fræsning · Haas Mini Mill',focus:"Holdbarhed til brug i undervisningen",intro:"En GF1-lærer bad mig fremstille en holdbar ringbøjer til undervisningen. Eleverne skulle opleve, hvordan en ske kan blive til en ring, og hvor konkret konstruktion og fremstilling kan være. Hun kendte mit arbejde fra tidligere småopgaver og henvendte sig direkte til mig.",challenge:"Læreren havde købt en 3D-printet ringbøjer for at afprøve idéen, men den gik i stykker, allerede da hun selv bukkede den første ring. Opgaven var at fremstille et lignende værktøj i metal, som kunne holde til brug i undervisningen.",solution:"Jeg begyndte med at måle det eksisterende værktøj op og modellere alle delene i Fusion 360. Konstruktionen blev udført i aluminium med selve bukkeren og cylindrene i stål. Jeg fremstillede alle delene på vores Haas Mini Mill, hvor jeg har min største erfaring.",learning:"Projektet gav mig erfaring med at omsætte et konkret behov til et færdigt værktøj: fra opmåling af en eksisterende model til CAD, materialevalg og CNC-fremstilling.",docs:[]},
tac:{extra:[["Design og ansvar", "Min ven stod for designet i Autodesk Inventor. Jeg stod for fremstillingen efter at have afklaret mulighederne med vores underviser."], ["Resultatet", "Efter fremstillingen fik han delen med til afprøvning. Et par dage senere sendte han et billede og fortalte, at den fungerede rigtig godt."]],title:'Tac Table',index:'03 / CNC-BEARBEJDNING',image:'tac-table.webp',material:'EN AW-6082-T6',process:'CNC-fræsning · Haas Mini Mill',focus:'Opspænding og planhed',intro:"En god ven, som jeg mødte gennem uddannelsen, havde designet et Tac Table i Autodesk Inventor. Han er uddannet våbenmekaniker og sportsskytte og skulle bruge pladen til montering af kikkert og andet sigteudstyr. Han spurgte, om vi kunne fremstille den.",challenge:"Den største udfordring var at bevare pladens planhed under fræsningen, så den ikke bukkede under bearbejdningen.",solution:"Jeg undersøgte først mulighederne sammen med vores underviser, og vi vurderede, at delen kunne fremstilles. Under fræsningen arbejdede jeg med mange lette gennemløb og understøttede emnet med en Machinist Jack for at holde det stabilt.",learning:"Projektet gav mig erfaring med at fremstille en del ud fra en andens konstruktion og med betydningen af understøtning og bearbejdningsforløb for pladens planhed.",docs:[['SETUP SHEET','Tac Table · værktøjer og operationer','setup-tactable.html']]}
};
const dialog=document.querySelector('#project-dialog');let opener=null;
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',event=>{
if(event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();
const p=projects[button.dataset.project];opener=button;
document.querySelector('#project-index').textContent=p.index;
document.querySelector('#project-content').innerHTML=`<figure class="dialog-visual"><img src="images/${p.image}" alt="Visualisering af ${p.title}" width="1536" height="1024"><figcaption>AI-visualisering baseret på min CAD-rendering.</figcaption></figure><div class="dialog-copy"><h2 id="project-title">${p.title}</h2><p class="dialog-intro">${p.intro}</p><dl class="project-facts"><div><dt>Materiale</dt><dd>${p.material}</dd></div><div><dt>Proces</dt><dd>${p.process}</dd></div><div><dt>Fokus</dt><dd>${p.focus}</dd></div></dl><div class="project-story">${(p.extra||[]).map(([heading,text])=>`<section><h3>${heading}</h3><p>${text}</p></section>`).join('')}<section><h3>Udfordringen</h3><p>${p.challenge}</p></section><section><h3>Min fremgangsmåde</h3><p>${p.solution}</p></section></div><section class="project-learning"><h3>Det tager jeg med videre</h3><p>${p.learning}</p></section>${p.docs.length?`<section class="project-documents"><h3>Dokumentation</h3><p>${p.docs.length===3?'Tre FAI-rapporter (First Article Inspection) med mål og kontrolresultater.':'Opspænding, værktøjsliste og operationsrækkefølge.'}</p><div class="doc-links">${p.docs.map(d=>`<a href="documents/${d[2]}"><span class="doc-kind">${d[0]}</span><strong>${d[1]}</strong><span aria-hidden="true">→</span></a>`).join('')}</div></section>`:''}</div>`;
dialog.showModal();document.body.classList.add('dialog-open');dialog.scrollTop=0;dialog.querySelector('.dialog-close').focus();
}));
dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close();});
dialog.addEventListener('close',()=>{document.body.classList.remove('dialog-open');opener?.focus();});
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');
function closeMenu(){menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open');}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus();}});
const form=document.querySelector('#request-form'),result=document.querySelector('#template-result'),output=document.querySelector('#request-template'),status=document.querySelector('#template-status'),stale=document.querySelector('#template-stale');
const types={prototype:['Prototype','Jeg vil gerne have hjælp til en prototype.','Formål og hvad prototypen skal afprøve'],part:['Enkeltstående del / reservedel','Jeg vil gerne have hjælp til en enkeltstående del eller reservedel.','Funktion, mål og hvad delen skal passe sammen med'],series:['Mindre serie','Jeg vil gerne have vurderet en mindre serie.','Funktion, ensartethed og eventuelle gentagne leverancer'],cad:['CAD / konstruktion','Jeg vil gerne have hjælp til CAD og konstruktion.','Funktion, pladsforhold og ønsket filformat'],fixture:['Fikstur / specialværktøj','Jeg vil gerne have hjælp til et fikstur eller specialværktøj.','Emnet, belastningen og hvordan værktøjet skal bruges'],other:['Afklaring af opgave','Jeg har en idé, som jeg gerne vil have hjælp til at afklare.','Min idé og det, jeg har brug for hjælp til']};
form.addEventListener('input',()=>{if(!result.hidden)stale.hidden=false;});
form.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),type=types[f.get('type')],get=k=>String(f.get(k)||'').trim();const assets=f.getAll('assets');
output.value=get('contact-kind')==='job'?`Emne: Job og faglig dialog\n\nHej Glen,\n\n${get('job-description')||'[Beskriv muligheden eller det, du gerne vil tale om]'}\n\nJeg hører gerne fra dig.\n\nVenlig hilsen\n${get('name')||'[Dit navn]'}${get('email')?'\n'+get('email'):''}`:`Emne: Forespørgsel — ${type[0]}\n\nHej Glen,\n\n${type[1]}\n\n${type[2]}:\n${get('description')||'[Beskriv opgaven her]'}\n\nMateriale: ${get('material')}\nAntal: ${get('quantity')||'Ikke afklaret'}\nØnsket levering: ${get('deadline')||'Efter aftale'}\n\nGrundlag, jeg kan sende:\n${assets.length?assets.map(x=>'• '+x).join('\n'):'Jeg har endnu ikke tegninger eller filer klar.'}\n\nKritiske mål og tolerancer: [Angiv krav, eller skriv at de skal afklares]\n\nKan du vurdere, om opgaven passer til dine muligheder, og hvilket grundlag du eventuelt mangler?\n\nVenlig hilsen\n${get('name')||'[Dit navn]'}${get('email')?'\n'+get('email'):''}`;
result.hidden=false;stale.hidden=true;status.textContent='Udkastet er klar. Tilpas teksten, kopiér den, og send den fra din egen mail.';output.focus();
});
document.querySelector('#copy-template').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(output.value);status.textContent='Teksten er kopieret.';}catch{output.focus();output.select();status.textContent='Teksten er markeret. Brug Kopiér på din enhed, eller hent tekstfilen.';}});
document.querySelector('#download-template').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([output.value],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='datum-forespoergsel.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Dit beskedudkast er hentet som tekstfil.';});




document.querySelector("#copy-email").addEventListener("click",async()=>{
 const message=document.querySelector("#email-copy-status");
 const fallback=document.querySelector("#email-copy-fallback");
 try{await navigator.clipboard.writeText("datumprototyping@gmail.com");fallback.hidden=true;message.textContent="Mailadressen er kopieret.";}
 catch{fallback.hidden=false;fallback.focus();fallback.select();message.textContent="Adressen er markeret. Vælg Kopiér på din enhed.";}
});


function setContactKind(kind){
 document.querySelector('[name="contact-kind"][value="'+kind+'"]').checked=true;
 for(const [id,active] of [['task-fields',kind==='task'],['job-fields',kind==='job']]){const field=document.getElementById(id);field.hidden=!active;field.disabled=!active;}
 if(!result.hidden)stale.hidden=false;
}
form.querySelectorAll('[name="contact-kind"]').forEach(r=>r.addEventListener('change',()=>setContactKind(r.value)));
document.querySelectorAll('[data-contact-kind]').forEach(a=>a.addEventListener('click',()=>setContactKind(a.dataset.contactKind)));
form.addEventListener('invalid',e=>{const details=e.target.closest('details');if(details)details.open=true;},true);
